name: social_app_tutorial
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-118.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_advanced_avatar: ^1.5.0
  http: ^1.0.0
  intl: ^0.18.1
  path_provider: ^2.0.15
  # json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # json_serializable: ^6.7.0
  # build_runner: ^2.4.4

flutter:
  uses-material-design: true

  assets:
  - assets/fonts/
  - assets/data/
  - assets/avatar/
  - assets/images/
  - assets/images/2.0x/
  - assets/images/3.0x/

  fonts:
    - family: avenir
      fonts:
        - asset: assets/fonts/avenir/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/avenir/Metropolis-Bold.otf
          weight: 800