name: social_app_tutorial
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-118.0.dev <4.0.0"

dependencies:
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_advanced_avatar: ^1.5.0
  flutter_bloc: ^8.1.3
  go_router: ^8.0.5
  http: ^1.0.0
  intl: ^0.18.1
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/data/
    - assets/avatar/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

  fonts:
    - family: avenir
      fonts:
        - asset: assets/fonts/avenir/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/avenir/Metropolis-Bold.otf
          weight: 800
